language: android
sudo: false
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-21

  licenses:
      - 'android-sdk-license-.+'

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
#before_script:
#  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#  - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &
#  - android-wait-for-emulator
#  - adb devices
#  - adb shell input keyevent 82 &

script:
  #- android list target
  #- ./gradlew connectedAndroidTest
  - ./gradlew assembleDebug

notifications:
  email: false
